# Generated by Django 4.1.13 on 2026-05-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swaplearn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="credit",
            field=models.IntegerField(default=10),
        ),
    ]
