# Generated by Django 4.1.13 on 2026-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swaplearn", "0002_alter_userprofile_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status",
            field=models.CharField(default="sent", max_length=20),
        ),
        migrations.AddField(
            model_name="message",
            name="type",
            field=models.CharField(default="text", max_length=20),
        ),
    ]
